using System;
using System.IO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using Microsoft.Azure.WebJobs.Extensions.WebPubSub;
using Microsoft.Azure.WebPubSub.Common;
using PubSub.Model;
using System.Collections.Generic;
using Microsoft.Azure.Cosmos;
using PubSub.Service;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace PubSub
{
  public class Game
  {
    private CosmosClient _cosmosClient;
    private GameService _gameService;

    public Game(CosmosClient cosmosClient, GameService gameService)
    {
      _cosmosClient = cosmosClient;
      _gameService = gameService;
    }

    [FunctionName("game")]
    public async Task<UserEventResponse> Run(
        [WebPubSubTrigger("game", WebPubSubEventType.User, "message")] UserEventRequest request,
        BinaryData data,
        WebPubSubDataType dataType,
        WebPubSubConnectionContext connectionContext,
        [WebPubSub(Hub = "game")] IAsyncCollector<WebPubSubAction> actions,
        ILogger logger)
    {
      var gameContextService = new GameContextService(connectionContext);
      logger.LogInformation($"[GAME CONTEXT] [{JsonConvert.SerializeObject(gameContextService)}]");

      var gameEvent = data.ToObjectFromJson<GameEvent>();
      logger.LogInformation($"[GAME EVENT] [{JsonConvert.SerializeObject(gameEvent)}]");

      var userId = request.ConnectionContext.UserId;

      // // this will be removed, group will be auto generated by shortid
      var (group, suit) = gameEvent.Data;

      logger.LogInformation($"[GAME][GET] Getting..");
      var game = await _gameService.GetGame(group);
      logger.LogInformation($"[GAME][GET] Received game [{JsonConvert.SerializeObject(game)}]");

      if (gameEvent.EventType == EventType.CREATE && game == null)
      {
        logger.LogInformation("[CREATE] Creating game..");
        var createdGame = await _gameService.CreateGameAsync(group, userId, suit);
        logger.LogInformation($"[CREATE] Created game! [{JsonConvert.SerializeObject(createdGame)}]");
        gameContextService.UpdateGameContext(group, suit);
        await actions.AddAsync(WebPubSubAction.CreateAddUserToGroupAction(userId, group));
        // change id to shortid, dont allow it to be create
      }
      else if (gameEvent.EventType == EventType.JOIN && game != null)
      {
        logger.LogInformation($"[JOIN] Joining game..");
        logger.LogInformation($"[JOIN][GROUP] {group}");
        logger.LogInformation($"[JOIN][SUIT] {suit}");
        var updatedGame = await _gameService.JoinGame(userId, suit, game);
        logger.LogInformation($"[JOIN] Joined game [{JsonConvert.SerializeObject(updatedGame)}]");
        gameContextService.UpdateGameContext(group, suit);
        await actions.AddAsync(WebPubSubAction.CreateAddUserToGroupAction(userId, group));
      }
      else if (gameEvent.EventType == EventType.START)
      {
        logger.LogInformation("[START] HIT START!");
        // to only group
        await actions.AddAsync(WebPubSubAction.CreateSendToGroupAction(
          gameContextService.Instance.Group,
          BinaryData.FromString($"[{userId}] Group only!"),
          dataType
        ));
      }
      else
      {
        throw new Exception("Invalid event");
      }

      // // to all
      await actions.AddAsync(WebPubSubAction.CreateSendToAllAction(
          BinaryData.FromString($"[{userId}] {data.ToString()}"),
          dataType));

      var userEventResponse = new UserEventResponse
      {
        Data = BinaryData.FromString("[SYSTEM] General Response"),
        DataType = WebPubSubDataType.Text,
      };

      userEventResponse.SetState(GameConstants.GAME_CONTEXT, gameContextService);

      return userEventResponse;
    }
  }
}
