name: Provision resource group

on:
  workflow_call:
    inputs:
      resourcegroup:
        required: true
        type: string
      resourcegroup-location:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

jobs:
  provision-resourcegroup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create resource group
        run: |
          az group create --name ${{ inputs.resourcegroup }} --location ${{ inputs.resourcegroup-location }} --output none
